### ISSUE TITLE
Failed to do mobfileCompaction for the table with a none default namespace.

### ISSUE THREAD

**Issue by tiffanyTown** [intel-hadoop/HBase-LOB#19]
java.io.IOException: Unable to load configured mob file compactor 'org.apache.hadoop.hbase.mob.filecompactions.PartitionedMobFileCompactor'
        at org.apache.hadoop.hbase.master.MobFileCompactionChore.chore(MobFileCompactionChore.java:90)
        at org.apache.hadoop.hbase.ScheduledChore.run(ScheduledChore.java:192)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.UnsupportedOperationException: Constructor threw an exception for org.apache.hadoop.hbase.mob.filecompactions.PartitionedMobFileCompactor
        at org.apache.hadoop.hbase.util.ReflectionUtils.instantiate(ReflectionUtils.java:54)
        at org.apache.hadoop.hbase.util.ReflectionUtils.instantiateWithCustomCtor(ReflectionUtils.java:34)
        at org.apache.hadoop.hbase.master.MobFileCompactionChore.chore(MobFileCompactionChore.java:84)
        ... 8 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.hbase.util.ReflectionUtils.instantiate(ReflectionUtils.java:46)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: my_ns:AdminOperationTest2
        at org.apache.hadoop.fs.Path.initialize(Path.java:206)
        at org.apache.hadoop.fs.Path.<init>(Path.java:172)
        at org.apache.hadoop.fs.Path.<init>(Path.java:89)
        at org.apache.hadoop.hbase.mob.filecompactions.PartitionedMobFileCompactor.<init>(PartitionedMobFileCompactor.java:102)
        ... 15 more
Caused by: java.net.URISyntaxException: Relative path in absolute URI: my_ns:AdminOperationTest2
        at java.net.URI.checkPath(URI.java:1804)
        at java.net.URI.<init>(URI.java:752)
        at org.apache.hadoop.fs.Path.initialize(Path.java:203)

**Comment by tiffanyTown** [comment]
verified.
